site_name: DMECC - Help Documentation
site_url: https://dme-softwaresolutions.github.io/clientcare-help

nav:
    - Home: index.md
    - Support Worker Guides:
        - Dashboard: sw_dashboard.md
        - My Account: sw_myaccount.md
        - Clients: sw_clients.md
        - Work: sw_work.md
        - Resources: sw_resources.md
    - Administrator Guides:
        - Dashboard - Under Construction: admin_dashboard.md
        - My Account - Under Construction: admin_myaccount.md
    - Markdown Cheatsheet: md_sample.md
theme:
    name: windmill
