site_name: DMECC - Help Docs
site_url: https://dme-softwaresolutions.github.io/clientcare-help

nav:
    - Home: index.md
    - User Guide: profile.md
    - Editting your Profile: profile.md
        - Editting your Profile: profile.md
        - Editting your Profile: profile.md
        - Editting your Profile: profile.md
       
theme: 
    name: readthedocs
