site_name: DMECC - Help Docs
site_url: https://dme-softwaresolutions.github.io/clientcare-help

nav:
    - Home: index.md
    - Support Worker Guides:
        - Dashboard: sw/dashboard.md
        - My Account: sw/myaccount.md
        
